travis:
  secure:
    BINSTAR_TOKEN: kIWICtZwz/Brj2fdA9WEi82LwOn+smwWNExGXPluwlguo/CIM530yijGLpXPHmwwS1ETxsbihPix1ImZXP6dV7Xt55iI4X+kUjwgjDrw5lUZAftqYFI9GC8CgcLyQILlwx8MAf7gfFK0H1UD117EV+QJAzEOzjHSeNzulcJ0we4VQS8SeBhHVE8LkJ+YUaHjpk5THUT/hvynPe0ghI1fEQJUZnQPDigS1xQzyF1d3hK6Qvl3jlgvVLX7V9kbPxFXsy9MtqyWFiHmr79vCgyDWaR8Ne1Jk7KFY7aQbpCnZkDRLrTPJP0DkvfRN2tZX7L6aheZhLW2tVTIX21WMH/db2gkXj682ZpQHq1NNCo9qn5ZyH2zhrKd16JJOiGWPLknl4Gzf/7XUFLy6gZSoEHsIyA2s3SOhik9fkzEB8biZQip5dnGjiyCeOM/BhQz9TSicJca+bncROroy7jWRUjbIawhd4bSbcm+4iIi3cfiB4nDaaktQVTa16/N7cNaXrBLonLZdu0yJtt6jISwVcjJBGp7DbqGJZenY+G/nQU5JgWh2pW2MywtfzCDcNjZXNbkaWpEK2IDGu79OUHfG+ga30Wo3cGImB+GWYajm/nCGO+m5tpdwdpdeAemKj7NXjsuRYLMy9qV1mo9jjEsGfRRY4wCXuDmgjV9EVMfY9IYv6I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
