travis:
  secure:
    BINSTAR_TOKEN: tgF1nd3rwWiR3hNqvHskXzYoV+BDaLr42fOsda0Bm5f/ID1gtVs1YA56SZmfdOs3IQBGGqX98Rafu486KBBku2CpwvI2TZpycK2WC7yBNlADN0/uS92DhB+lMUKmELFqRQneObTKj6X1EAbHOR4ELoaMvvmb1y9uhqQhDGM2tVGy7ytq2JFL6g0n0Bz1kSPTMfdpayVfgNYIh48RNZSrHPaiFayYvguctuihPbdT3UlFLTZOY2Y44f4AllKnKd+6Nh2um/Ojtt1Qy+iUNdtIuD2T/xJ1GSfnNZKJsFjubGGwEts4RtgPuOOOh+wXyBy4cb0F0yfZlW2i6J06AiBkZx4+wCwMEAJSpJTWoVDPHz1BtSu7sb1qPdd4muLId1BC+fEosIfmmB+YZWdWeFgE6laOFT2GUJQ3Q84DZtgr6CAScgWTvF/OUTln7x7p0Vtj1ZTnfmBV/R8IL41iStGF7xmVznmpAwOGKFBjVKoYnUCmNzV9cqzkE6S8DWvbLCAn8cnL04gNFS4E8qWwejR9o1mQG0waeUmWDa27lPTyA87Eb8iy4AdGRAewxtD4JBTz28sXruoayxmiYbmabAyHp+KKMx/88CBE9UPwYV7T8A98ku++GqA5v4MgOO3rmHtxdkNSsqQ8N1cFpP+/xZVQmIC0HimTZNR+OaFLkzFd7nY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
